# Site wide configuration
title: Stefan Stranger's Blog
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog. I work at Microsoft as a Consultant. 
  You can find some of my open source projects on Github.
  I like to share my knowledge about Azure, PowerShell and DevOps
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stefanstranger.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Owner configuration
# name and email are required (change code to remove these)
# (leave the rest blank to disable the corresponding sharing button)
owner:
    name: Stefan Stranger
    github: stefanstranger
    twitter: sstranger
    linkedin: stefanstranger
    facebook:
    google_plus:
    youtube:

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'stefanstranger'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-paginate

# Exclude
exclude: ['README.md']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/